### ISSUE TITLE
hot reload error

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#326]
hot reload gives the following error. it seems to be related to Akka HTTP. but I'm not sure.

```
my-app[ERROR] Uncaught error from thread [my-app-akka.actor.default-dispatcher-5]: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[my-app]
my-app[ERROR] java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
my-app[ERROR]    at korolev.internal.DevMode$ForRenderContext.loadRenderContext(DevMode.scala:46)
my-app[ERROR]    at korolev.internal.ApplicationInstance.<init>(ApplicationInstance.scala:59)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$15(SessionsService.scala:128)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app [2020-06-25 22:52:09,088] [ERROR] [akka.actor.ActorSystemImpl] [SECURITY] [my-app-akka.actor.default-dispatcher-17] - Uncaught error from thread [my-app-akka.actor.default-dispatcher-5]: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[my-app] {akkaAddress=akka://my-app@127.0.0.1:2551, sourceThread=my-app-akka.actor.default-dispatcher-5, akkaSource=akka.actor.ActorSystemImpl(my-app), sourceActorSystem=my-app, akkaTimestamp=20:52:09.084UTC}
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app   at korolev.internal.DevMode$ForRenderContext.loadRenderContext(DevMode.scala:46)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app   at korolev.internal.ApplicationInstance.<init>(ApplicationInstance.scala:59)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$15(SessionsService.scala:128)
my-app[ERROR]    at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$14(SessionsService.scala:123)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app   at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app[ERROR]    at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app   at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$12(SessionsService.scala:120)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$14(SessionsService.scala:123)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$12$adapted(SessionsService.scala:119)
my-app   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app   at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app[ERROR]    at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.appsFactory(SessionsService.scala:119)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$5(SessionsService.scala:76)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app   at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$12(SessionsService.scala:120)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$appsFactory$12$adapted(SessionsService.scala:119)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app   at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app[ERROR]    at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$2(SessionsService.scala:72)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$2$adapted(SessionsService.scala:71)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app   at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app   at korolev.server.internal.services.SessionsService.appsFactory(SessionsService.scala:119)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$5(SessionsService.scala:76)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app   at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app[ERROR]    at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app[ERROR]    at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app[ERROR]    at korolev.server.internal.services.SessionsService.findAppOrCreate(SessionsService.scala:71)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at korolev.server.internal.services.MessagingService.webSocketMessaging(MessagingService.scala:65)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at korolev.server.internal.KorolevServiceImpl.ws(KorolevServiceImpl.scala:69)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app[ERROR]    at korolev.akka.package$.$anonfun$configureWsRoute$4(package.scala:69)
my-app   at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app[ERROR]    at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$2(FutureDirectives.scala:97)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$2(SessionsService.scala:72)
my-app[ERROR]    at akka.http.scaladsl.server.Directive.$anonfun$recover$4(Directive.scala:110)
my-app   at korolev.server.internal.services.SessionsService.$anonfun$findAppOrCreate$2$adapted(SessionsService.scala:71)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
my-app[ERROR]    at akka.http.scaladsl.server.Directive.$anonfun$recover$2(Directive.scala:110)
my-app   at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:67)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
my-app[ERROR]    at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
my-app   at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:84)
my-app[ERROR]    at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
my-app   at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:64)
my-app   at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:34)
my-app   at korolev.server.internal.services.SessionsService.findAppOrCreate(SessionsService.scala:71)
my-app   at korolev.server.internal.services.MessagingService.webSocketMessaging(MessagingService.scala:65)
my-app   at korolev.server.internal.KorolevServiceImpl.ws(KorolevServiceImpl.scala:69)
my-app[ERROR]    at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at korolev.akka.package$.$anonfun$configureWsRoute$4(package.scala:69)
my-app   at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$2(FutureDirectives.scala:97)
my-app   at akka.http.scaladsl.server.Directive.$anonfun$recover$4(Directive.scala:110)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at akka.http.scaladsl.server.Directive.$anonfun$recover$2(Directive.scala:110)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app   at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
my-app   at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
my-app[ERROR]    at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
my-app   at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
my-app[ERROR]    at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1400)
my-app   at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1400)
my-app[ERROR]    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
my-app   at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
my-app[ERROR]    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
my-app   at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
my-app[ERROR]    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
my-app   at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
my-app[ERROR]    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
my-app   at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
my-app[ERROR]    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
my-app   at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
my-app[ERROR]    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
my-app   at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
my-app[ERROR]    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
my-app   at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
my-app[ERROR]    at akka.actor.Actor.aroundReceive(Actor.scala:535)
my-app   at akka.actor.Actor.aroundReceive(Actor.scala:535)
my-app[ERROR]    at akka.actor.Actor.aroundReceive$(Actor.scala:533)
my-app   at akka.actor.Actor.aroundReceive$(Actor.scala:533)
my-app[ERROR]    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
my-app   at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
my-app[ERROR]    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
my-app   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
my-app[ERROR]    at akka.actor.ActorCell.invoke(ActorCell.scala:547)
my-app   at akka.actor.ActorCell.invoke(ActorCell.scala:547)
my-app[ERROR]    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
my-app   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
my-app[ERROR]    at akka.dispatch.Mailbox.run(Mailbox.scala:231)
my-app   at akka.dispatch.Mailbox.run(Mailbox.scala:231)
my-app[ERROR]    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
my-app   at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
my-app[ERROR]    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
my-app   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
my-app   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
my-app   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
my-app   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
my-app[ERROR]    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
my-app [2020-06-25 22:52:09,098] [INFO] [akka.cluster.Cluster] [akkaMemberChanged] [my-app-akka.actor.default-dispatcher-17] - Cluster Node [akka://my-app@127.0.0.1:2551] - Marked address [akka://my-app@127.0.0.1:2551] as [Leaving] {akkaRemoteAddressUid=-4874348631067046149, akkaAddress=akka://my-app@127.0.0.1:2551, sourceThread=my-app-akka.actor.internal-dispatcher-2, akkaSource=Cluster(akka://my-app), sourceActorSystem=my-app, akkaRemoteAddress=akka://my-app@127.0.0.1:2551, akkaTimestamp=20:52:09.098UTC, akkaMemberStatus=Leaving}
```

**Comment by fomkin** [comment]
I sure it is related to Java version. Looks like I build Korolev view Java 13. Again.

**Comment by Zhen-hao** [comment]
it's working in 0.16.1

**Comment by Zhen-hao** [comment]
> it's working in 0.16.1

I was wrong. I am actually using 0.15.2.
