### ISSUE TITLE
Start from g8 template fails on windows on cmd prompt, but it works in the Ubuntu that comes with windows

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#335]
sbt new fomkin/korolev.g8

scala -version
Scala code runner version 2.13.3 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.

```
C:\home\projects\web>java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

C:\home\projects\web>sbt update compile
[info] Loading global plugins from C:\Users\philip\.sbt\1.0\plugins
[info] Loading settings for project web-build from plugins.sbt ...
[info] Loading project definition from C:\home\projects\web\project
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error]         at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error]         at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:457)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error]         at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error]         at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error]         at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error]         at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error]         at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5833)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5536)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1868)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5538)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
[error]         at sbt.compiler.Eval.$anonfun$compileAndLoad$1(Eval.scala:248)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:282)
[error]         at sbt.compiler.Eval.compile$1(Eval.scala:248)
[error]         at sbt.compiler.Eval.compileAndLoad(Eval.scala:253)
[error]         at sbt.compiler.Eval.evalCommon(Eval.scala:218)
[error]         at sbt.compiler.Eval.eval(Eval.scala:128)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:239)
[error]         at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$2(EvaluateConfigurations.scala:158)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:294)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:156)
[error]         at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1136)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1144)
[error]         at scala.collection.MapLike.getOrElse(MapLike.scala:127)
[error]         at scala.collection.MapLike.getOrElse$(MapLike.scala:125)
[error]         at scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error]         at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1143)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1151)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at sbt.internal.Load$.loadFiles$1(Load.scala:1151)
[error]         at sbt.internal.Load$.discoverProjects(Load.scala:1165)
[error]         at sbt.internal.Load$.discover$1(Load.scala:862)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:937)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:688)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error]         at sbt.internal.Load$.loadAll(Load.scala:562)
[error]         at sbt.internal.Load$.loadURI(Load.scala:492)
[error]         at sbt.internal.Load$.load(Load.scala:471)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:251)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:119)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error]         at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error]         at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:457)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error]         at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error]         at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error]         at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error]         at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error]         at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5833)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5536)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1868)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5538)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
[error]         at sbt.compiler.Eval.$anonfun$compileAndLoad$1(Eval.scala:248)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:282)
[error]         at sbt.compiler.Eval.compile$1(Eval.scala:248)
[error]         at sbt.compiler.Eval.compileAndLoad(Eval.scala:253)
[error]         at sbt.compiler.Eval.evalCommon(Eval.scala:218)
[error]         at sbt.compiler.Eval.eval(Eval.scala:128)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:239)
[error]         at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$2(EvaluateConfigurations.scala:158)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:294)
[error]         at sbt.internal.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:156)
[error]         at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1136)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1144)
[error]         at scala.collection.MapLike.getOrElse(MapLike.scala:127)
[error]         at scala.collection.MapLike.getOrElse$(MapLike.scala:125)
[error]         at scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error]         at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1143)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1151)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at sbt.internal.Load$.loadFiles$1(Load.scala:1151)
[error]         at sbt.internal.Load$.discoverProjects(Load.scala:1165)
[error]         at sbt.internal.Load$.discover$1(Load.scala:862)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:937)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:688)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error]         at sbt.internal.Load$.loadAll(Load.scala:562)
[error]         at sbt.internal.Load$.loadURI(Load.scala:492)
[error]         at sbt.internal.Load$.load(Load.scala:471)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:251)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:119)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] Use 'last' for the full log.
q
```

**Comment by PhilAndrew** [comment]
For Ubuntu Windows WSL, the Ubuntu which is kind of part of Windows now

```
[info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.2. Compiling...
8 warnings
[info]   Compilation completed in 8.62s.
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/philip/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.7/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[success] Total time: 98 s, completed Nov 26, 2020, 8:55:54 AM
```

**Comment by fomkin** [comment]
Hi!

I don't think this error is related to Korolev. Looks like an error in SBT.

P.S. Welcome back!
