### ISSUE TITLE
0.17-M1 unable to start

### ISSUE THREAD

**Issue by ranglang** [fomkin/korolev#344]
```

[ERROR] [12/22/2020 17:53:17.134] [hello-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(hello)] Error during processing of request: '[Ljava.lang.String;@56eb1808 (of class [Ljava.lang.String;)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
scala.MatchError: [Ljava.lang.String;@56eb1808 (of class [Ljava.lang.String;)
        at korolev.web.Request.$anonfun$parsedCookie$1(Request.scala:38)
        at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
        at korolev.web.Request.parsedCookie$lzycompute(Request.scala:37)
        at korolev.web.Request.parsedCookie(Request.scala:33)
        at korolev.web.Request.cookie(Request.scala:47)
        at korolev.server.internal.services.SessionsService.initSession(SessionsService.scala:45)
        at korolev.server.internal.services.ServerSideRenderingService.serverSideRenderedPage(ServerSideRenderingService.scala:36)
        at korolev.server.internal.KorolevServiceImpl.http(KorolevServiceImpl.scala:58)
        at korolev.akka.package$.handleHttpResponse(package.scala:133)
        at korolev.akka.package$.$anonfun$configureHttpRoute$2(package.scala:109)
        at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:45)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1401)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
```

**Comment by fomkin** [comment]
Could you provide demo to reproduce?

**Comment by ranglang** [comment]
> Could you provide demo to reproduce?

https://github.com/ranglang/mill-docker 

cd example; mill -w hello.runBackground

**Comment by greenhost87** [comment]
I try run your example and it start without any problem

**Comment by fomkin** [comment]
Looks like you browser has corrupted cookies. Try to open app from another browser (or clear cookies). However we should to have failover for this case.
