### ISSUE TITLE
BadRequestException: Session initialization in progress

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#364]
with version `0.17-M3` I see the following runtime exception when loading Korolev states from state storage after server reboot.
It is not clear to me what the root cause is and where I should handle it.

```
[info] [2021-01-31 21:06:25,649] [ERROR] [akka.actor.ActorSystemImpl] [] [nt-ui-akka.actor.default-dispatcher-26] - Error during processing of request: 'Session initialization in progress. Please try again later.'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler. {akkaAddress=akka://nt-ui@127.0.0.1:2551, sourceThread=nt-ui-akka.actor.default-dispatcher-42, akkaSource=akka.actor.ActorSystemImpl(nt-ui), sourceActorSystem=nt-ui, akkaTimestamp=20:06:25.648UTC}
[info] korolev.server.internal.BadRequestException: Session initialization in progress. Please try again later.
[info]  at korolev.server.internal.services.SessionsService.$anonfun$createAppIfNeeded$5(SessionsService.scala:83)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:69)
[info]  at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
[info]  at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:86)
[info]  at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:66)
[info]  at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:36)
[info]  at korolev.server.internal.services.SessionsService.$anonfun$createAppIfNeeded$2(SessionsService.scala:75)
[info]  at korolev.server.internal.services.SessionsService.$anonfun$createAppIfNeeded$2$adapted(SessionsService.scala:74)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at korolev.effect.Effect$FutureEffect$$anon$1.execute(Effect.scala:69)
[info]  at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
[info]  at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:140)
[info]  at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:86)
[info]  at korolev.effect.Effect$FutureEffect.flatMap(Effect.scala:66)
[info]  at korolev.effect.syntax$EffectOps.flatMap(syntax.scala:36)
[info]  at korolev.server.internal.services.SessionsService.createAppIfNeeded(SessionsService.scala:74)
[info]  at korolev.server.internal.services.MessagingService.webSocketMessaging(MessagingService.scala:73)
[info]  at korolev.server.internal.KorolevServiceImpl.ws(KorolevServiceImpl.scala:69)
[info]  at korolev.akka.package$.$anonfun$configureWsRoute$4(package.scala:72)
[info]  at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:51)
[info]  at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
[info]  at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
[info]  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
[info]  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
[info]  at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
[info]  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:25)
[info]  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
[info]  at akka.http.scaladsl.server.Route$.$anonfun$createAsyncHandler$1(Route.scala:110)
[info]  at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1402)
[info]  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
[info]  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:773)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788)
[info]  at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info]  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info]  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by fomkin** [comment]
I sure there is something wrong with it.

**Comment by fomkin** [comment]
@Zhen-hao I carefully looked up your [code](https://gist.github.com/Zhen-hao/a1b50cbeb04ece670144c297e9162e7d) and for now I have only one hypothesis.
1. The mailbox [replication](https://gist.github.com/Zhen-hao/a1b50cbeb04ece670144c297e9162e7d#file-distributeduistatecache-scala-L94) is inconsistent. The Actor receives `GetStatesForSession` before it catch up log replicas.
2. This leads to situation when StateManager successfully resolves, but snapshot is empty.
3. [Here](https://github.com/fomkin/korolev/blob/master/modules/korolev/src/main/scala/korolev/server/internal/services/SessionsService.scala#L123 ) Korolev tries to take TopLevel state and receives `NoSuchElementException`. WebSocket connection closes.
4. Korolev's client part tries to reopen connection, but session initilization was suddenly interrupted before (`NoSuchElementException` mentioned above had not be catched). Korolev's server thinks that session initialization still in progress.

You can check it by tracing [mailbox processing](https://gist.github.com/Zhen-hao/a1b50cbeb04ece670144c297e9162e7d#file-distributeduistatecache-scala-L97), and adding break point at the [place](https://github.com/fomkin/korolev/blob/master/modules/korolev/src/main/scala/korolev/server/internal/services/SessionsService.scala#L123) where Korolev try to receive top level state. I do not experienced in Akka Cluster so it's probable that I'am wrong.

**Comment by Zhen-hao** [comment]
Thank you so much for looking into this!

I will take some time to follow your advice and see if I can find out the
root cause of the problem.
After that, I'll send you my findings.

Best,
Zhenhao

**Comment by Zhen-hao** [comment]
I get this error every time I resume/continue in the debug after a stopping point. 
```
[2021-02-18 09:03:57,635] [ERROR] [akka.actor.ActorSystemImpl] [] [nt-ui-akka.actor.default-dispatcher-35] - Error during processing of request: 'There is no long-polling topic matching MhQmFlcl4yBYzNVkT76aLObMYf0p1sHpfPFf4zGjEoLuSRPfFEhr2uiJYaDglZ18-sbNlajGsr25hmzYNuxv8cVvwltSWeoGpI3uFhRjj2oKcYCUr2sT4PE3IjB3TuoYa'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler. {akkaAddress=akka://nt-ui@127.0.0.1:2551stop, sourceThread=nt-ui-akka.actor.default-dispatcher-50, akkaSource=akka.actor.ActorSystemImpl(nt-ui), sourceActorSystem=nt-ui, akkaTimestamp=08:03:57.629UTC}
java.lang.Exception: There is no long-polling topic matching MhQmFlcl4yBYzNVkT76aLObMYf0p1sHpfPFf4zGjEoLuSRPfFEhr2uiJYaDglZ18-sbNlajGsr25hmzYNuxv8cVvwltSWeoGpI3uFhRjj2oKcYCUr2sT4PE3IjB3TuoYa
	at korolev.server.internal.services.MessagingService.$anonfun$takeTopic$1(MessagingService.scala:127)
	at korolev.effect.Effect$FutureEffect.delay(Effect.scala:78)
	at korolev.effect.Effect$FutureEffect.delay(Effect.scala:66)
	at korolev.server.internal.services.MessagingService.takeTopic(MessagingService.scala:126)
	at korolev.server.internal.services.MessagingService.longPollingPublish(MessagingService.scala:66)
	at korolev.server.internal.KorolevServiceImpl.http(KorolevServiceImpl.scala:44)
	at korolev.akka.package$.handleHttpResponse(package.scala:137)
	at korolev.akka.package$.$anonfun$configureHttpRoute$2(package.scala:113)
	at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
2
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by Zhen-hao** [comment]
I don't see this problem any more.
