### ISSUE TITLE
MatchError when user has a cookie with empty value

### ISSUE THREAD

**Issue by valentiay** [fomkin/korolev#365]
Korolev application main page fails to load with Internal Server Error if user has a cookie with empty value. It is caused by MatchError while parsing cookies in korolev.web.Request. Korolev does not set cookies with empty values, but such cookies are valid and may be set by other application in the same domain. 

Here is an example of cURL which causes this problem:
```
curl 'http://localhost:8080/'  -H 'Cookie: deviceId=xxx; foo='
```
<details>
<summary>Server logs with stack trace</summary>

```
[ERROR] [02/10/2021 15:03:01.725] [default-akka.actor.default-dispatcher-43] [akka.actor.ActorSystemImpl(default)] Error during processing of request: '[Ljava.lang.String;@79c6dfd6 (of class [Ljava.lang.String;)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
scala.MatchError: [Ljava.lang.String;@79c6dfd6 (of class [Ljava.lang.String;)
	at korolev.web.Request.$anonfun$parsedCookie$1(Request.scala:38)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at korolev.web.Request.parsedCookie$lzycompute(Request.scala:37)
	at korolev.web.Request.parsedCookie(Request.scala:33)
	at korolev.web.Request.cookie(Request.scala:47)
	at korolev.server.internal.services.SessionsService.initSession(SessionsService.scala:45)
	at korolev.server.internal.services.ServerSideRenderingService.serverSideRenderedPage(ServerSideRenderingService.scala:36)
	at korolev.server.internal.KorolevServiceImpl.http(KorolevServiceImpl.scala:58)
	at korolev.akka.package$.handleHttpResponse(package.scala:137)
	at korolev.akka.package$.$anonfun$configureHttpRoute$2(package.scala:113)
	at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
	at akka.http.scaladsl.server.Route$.$anonfun$createAsyncHandler$1(Route.scala:110)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1400)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

</details>

This problem reproduces since 0.17.

Exception is thrown in [this line of code](https://github.com/fomkin/korolev/blob/master/modules/web/src/main/scala/korolev/web/Request.scala#L38), because `"foo=".split('=')` is a single element array. 

If you don't mind, I can fix it with adding patter-matching there.

**Comment by fomkin** [comment]
> If you don't mind, I can fix it with adding patter-matching there.

This would be awesome!
