### ISSUE TITLE
MatchError from evalJs

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#387]
I'm not sure if this is a new issue.

```scala
val newHeight: Int = 244
...
access.evalJs(js"""document.getElementById('myDivId').style.height = '${newHeight}px';""")
```
results in
```
[info] scala.MatchError: List(244) (of class scala.collection.immutable.$colon$colon)
[info]  at korolev.util.JsCode$.combine$1(JsCode.scala:54)
[info]  at korolev.util.JsCode$.apply(JsCode.scala:66)
[info]  at korolev.Context$Scope$JsCodeHelper.js(Context.scala:120)
```

**Comment by fomkin** [comment]
Thanks for report.

Workaround:
```scala
access.evalJs(js"""document.getElementById('myDivId').style.height = '${newHeight.toString}px';""")
````
